<?php

include_once('austrofeedr_hochwasser_messstellen_import.features.inc');

/**
 * feeds import csv in order to create default messstellen
 * procedure adapted from https://github.com/developmentseed/mn_world
 */

/**
 * Implementation of hook_enable().
 *
 * @todo: move this to a features_rebuild() callback.
 */
function austrofeedr_hochwasser_messstellen_import_enable() {
  $file = 'austrofeedr_hochwasser_messstellen.csv';
  $path = drupal_realpath('public://messstellen');
  if (file_prepare_directory($path, TRUE)) {
    $filepath = "{$path}/{$file}";

    // Copy messstellen csv to file directory, avoid using shell_exec() for
    // compatibility reasons.
    if (!file_exists($filepath)) {
      $src = file_get_contents(drupal_get_path('module', 'austrofeedr_hochwasser_messstellen_import') . "/feeds_import/{$file}");
      file_put_contents($filepath, $src);
    }

    // Import file, clear caches to verify to make sure 'locations' importer
    // is available when installing with Aegir.
    ctools_include('export');
    ctools_export_load_object_reset('feeds_importer');
    $source = feeds_source('af_hochwasser_messstellen');
    $source->addConfig(
      array(
        'FeedsFileFetcher' => array(
          'source' => $filepath
        ),
      )
    );
    while (FEEDS_BATCH_COMPLETE != $source->import());
  }
}

/**
 * Implementation of hook_disable().
 *
 * @todo: move this to a features_rebuild() callback.
 */
function austrofeedr_hochwasser_messstellen_import_disable() {
  // Dump all items from locations importer.
  $source = feeds_source('af_hochwasser_messstellen');
  $source->clear();
}
