<?php
/**
 * @file
 */

// Drupal needs this blank file.

/**
 * Implementation of hook_default_wsclient_service().
 */
function austrofeedr_hochwasser_fake_default_wsclient_service() {
  $services = array();

  // fake service
  $service = austrofeedr_hochwasser_pegelaktuell_import_get_wsclient_service();
  $service->name = 'hw_pegelaktuell_ehyd_fake';
  $service->label = 'Hochwasser Pegelaktuell eHYD Service Fake';
  $service->url = 'http://localhost/austrofeedr/sites/default/hochwasser_simulation/wmsgw_ybbs_0.xml';

  $service->operations['pegelaktuell']['result'] = array('type' => 'wsclient_hw_pegelaktuell_ehyd_service_pegelaktuell_result', 'label' => 'Pegelaktuell');
  $service->datatypes = array();

  $services[$service->name] = $service;

  return $services;
}