<?php
/**
 * @file
 */

include_once('austrofeedr_hochwasser_fake.features.inc');

// Drupal needs this blank file.

/**
 * Implementation of hook_default_wsclient_service().
 */
function austrofeedr_hochwasser_fake_default_wsclient_service() {
  $services = array();

  for($i=0; $i<5; $i++) {
    // fake service
    $service = austrofeedr_hochwasser_pegelaktuell_import_get_wsclient_service();
    $service->name = 'hw_pegelaktuell_ehyd_fake' . $i;
    $service->label = 'Hochwasser Pegelaktuell eHYD Service Fake ' . $i;

    //$service->url = "asdf" . url(drupal_get_path('module', "austrofeedr_hochwasser_fake") . '/hochwasser_simulation/wmsgw_ybbs_' . $i . '.xml', array('absolute' => TRUE));
    //$service->url = 'http://localhost/austrofeedr/sites/default/files/hochwasser_simulation/wmsgw_ybbs_' . $i . '.xml';
    global $base_url;
    $service->url = url($base_url . '/sites/default/files/hochwasser_simulation/wmsgw_ybbs_' . $i . '.xml', array('absolute' => TRUE));

    $service->operations['pegelaktuell']['result'] = array('type' => 'wsclient_hw_pegelaktuell_ehyd_service_pegelaktuell_result', 'label' => 'Pegelaktuell result');
    $service->datatypes = array();

    $services[$service->name] = $service;
  }

  return $services;
}


/**
 * Implements hook_rules_action_info().
 */
function austrofeedr_hochwasser_fake_rules_action_info() {
  return array(
    'austrofeedr_hochwasser_fake_cleanup' => array(
      'base' => 'austrofeedr_hochwasser_fake_cleanup_action',
      'label' => t('Hochwasser Fake Cleanup'),
      'group' => t('AustroFeedr'),
    ),
    'austrofeedr_hochwasser_fake_creator' => array(
      'base' => 'austrofeedr_hochwasser_fake_creator_action',
      'label' => t('Hochwasser Fake Creator'),
      'group' => t('AustroFeedr'),
      'parameter' => array(
        'entity' => array('type' => 'integer', 'label' => t('Counter')),
      ),
      'provides' => array(
        'result' => array(
          'type' => 'wsclient_hw_pegelaktuell_ehyd_service_pegelaktuell_result',
          'label' => t('Pegelaktuell result'),
        ),
      ),
    ),
  );
}

function austrofeedr_hochwasser_fake_cleanup_action() {
  $num_deleted = db_delete('field_data_field_hw_werte')
    ->condition('field_hw_werte_timestamp', time(), $operator = '>')
    ->execute();

  $num_deleted = db_delete('field_revision_field_hw_werte')
    ->condition('field_hw_werte_timestamp', time(), $operator = '>')
    ->execute();
}

function austrofeedr_hochwasser_fake_creator_action($counter) {
    if($counter < 0 || $counter > 4) {
      return;
    }
    $service = wsclient_service_load('hw_pegelaktuell_ehyd_fake' . $counter);
    $result = $service->pegelaktuell();
    return array('result' => $result);
}